/*
 * WARNING: do not edit!
 * Generated by makefile from configuration_one.h.in
 *
 * Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_CONFIGURATION_H
# define OPENSSL_CONFIGURATION_H
#ifdef OPENSSL_PRAGMA_ONCE
# pragma once
#endif

# ifdef  __cplusplus
extern "C" {
# endif

# ifdef OPENSSL_ALGORITHM_DEFINES
#  error OPENSSL_ALGORITHM_DEFINES no longer supported
# endif

/*
 * OpenSSL was configured with the following options:
 */

# define OPENSSL_CONFIGURED_API 30000
# ifndef OPENSSL_RAND_SEED_OS
#  define OPENSSL_RAND_SEED_OS
# endif
# ifndef OPENSSL_THREADS
#  define OPENSSL_THREADS
# endif
# ifndef OPENSSL_NO_ACVP_TESTS
#  define OPENSSL_NO_ACVP_TESTS
# endif
# ifndef OPENSSL_NO_AFALGENG
#  define OPENSSL_NO_AFALGENG
# endif
# ifndef OPENSSL_NO_ALT_MEMORY
#  define OPENSSL_NO_ALT_MEMORY
# endif
# ifndef OPENSSL_NO_APPS
#  define OPENSSL_NO_APPS
# endif
# ifndef OPENSSL_NO_ASAN
#  define OPENSSL_NO_ASAN
# endif
# ifndef OPENSSL_NO_ASM
#  define OPENSSL_NO_ASM
# endif
# ifndef OPENSSL_NO_CMS_SM2
#  define OPENSSL_NO_CMS_SM2
# endif
# ifndef OPENSSL_NO_CRYPTO_MDEBUG
#  define OPENSSL_NO_CRYPTO_MDEBUG
# endif
# ifndef OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
#  define OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
# endif
# ifndef OPENSSL_NO_DEVCRYPTOENG
#  define OPENSSL_NO_DEVCRYPTOENG
# endif
# ifndef OPENSSL_NO_DH_IGNORE_STRENGTH
#  define OPENSSL_NO_DH_IGNORE_STRENGTH
# endif
# ifndef OPENSSL_NO_DTO
#  define OPENSSL_NO_DTO
# endif
# ifndef OPENSSL_NO_EC_NISTP_64_GCC_128
#  define OPENSSL_NO_EC_NISTP_64_GCC_128
# endif
# ifndef OPENSSL_NO_EGD
#  define OPENSSL_NO_EGD
# endif
# ifndef OPENSSL_NO_EXTERNAL_TESTS
#  define OPENSSL_NO_EXTERNAL_TESTS
# endif
# ifndef OPENSSL_NO_FIPS_SECURITYCHECKS
#  define OPENSSL_NO_FIPS_SECURITYCHECKS
# endif
# ifndef OPENSSL_NO_FUZZ_AFL
#  define OPENSSL_NO_FUZZ_AFL
# endif
# ifndef OPENSSL_NO_FUZZ_LIBFUZZER
#  define OPENSSL_NO_FUZZ_LIBFUZZER
# endif
# ifndef OPENSSL_NO_GMTLS
#  define OPENSSL_NO_GMTLS
# endif
# ifndef OPENSSL_NO_INIT_NO_ATEXIT
#  define OPENSSL_NO_INIT_NO_ATEXIT
# endif
# ifndef OPENSSL_NO_KTLS
#  define OPENSSL_NO_KTLS
# endif
# ifndef OPENSSL_NO_KYBER
#  define OPENSSL_NO_KYBER
# endif
# ifndef OPENSSL_NO_MD2
#  define OPENSSL_NO_MD2
# endif
# ifndef OPENSSL_NO_MSAN
#  define OPENSSL_NO_MSAN
# endif
# ifndef OPENSSL_NO_PKCS7_SM2
#  define OPENSSL_NO_PKCS7_SM2
# endif
# ifndef OPENSSL_NO_PKCS8_SM2
#  define OPENSSL_NO_PKCS8_SM2
# endif
# ifndef OPENSSL_NO_PQC
#  define OPENSSL_NO_PQC
# endif
# ifndef OPENSSL_NO_PQCHYBRID
#  define OPENSSL_NO_PQCHYBRID
# endif
# ifndef OPENSSL_NO_RC5
#  define OPENSSL_NO_RC5
# endif
# ifndef OPENSSL_NO_RECORD_VERSION_COMPAT
#  define OPENSSL_NO_RECORD_VERSION_COMPAT
# endif
# ifndef OPENSSL_NO_SM2_ENVELOP
#  define OPENSSL_NO_SM2_ENVELOP
# endif
# ifndef OPENSSL_NO_SM2_EXCH
#  define OPENSSL_NO_SM2_EXCH
# endif
# ifndef OPENSSL_NO_SM2_NID_ECPUBLICKEY
#  define OPENSSL_NO_SM2_NID_ECPUBLICKEY
# endif
# ifndef OPENSSL_NO_SM9
#  define OPENSSL_NO_SM9
# endif
# ifndef OPENSSL_NO_SSL3
#  define OPENSSL_NO_SSL3
# endif
# ifndef OPENSSL_NO_SSL3_METHOD
#  define OPENSSL_NO_SSL3_METHOD
# endif
# ifndef OPENSSL_NO_TESTS
#  define OPENSSL_NO_TESTS
# endif
# ifndef OPENSSL_NO_TLS13_BRAINPOOLP256R1
#  define OPENSSL_NO_TLS13_BRAINPOOLP256R1
# endif
# ifndef OPENSSL_NO_TRACE
#  define OPENSSL_NO_TRACE
# endif
# ifndef OPENSSL_NO_TTO
#  define OPENSSL_NO_TTO
# endif
# ifndef OPENSSL_NO_UBSAN
#  define OPENSSL_NO_UBSAN
# endif
# ifndef OPENSSL_NO_UNIT_TEST
#  define OPENSSL_NO_UNIT_TEST
# endif
# ifndef OPENSSL_NO_UPLINK
#  define OPENSSL_NO_UPLINK
# endif
# ifndef OPENSSL_NO_WAPI
#  define OPENSSL_NO_WAPI
# endif
# ifndef OPENSSL_NO_WEAK_SSL_CIPHERS
#  define OPENSSL_NO_WEAK_SSL_CIPHERS
# endif
# ifndef OPENSSL_NO_X509_PUBKEY_DECODE_PROV
#  define OPENSSL_NO_X509_PUBKEY_DECODE_PROV
# endif
# ifndef OPENSSL_NO_X509_REQ_EXP_ATTR
#  define OPENSSL_NO_X509_REQ_EXP_ATTR
# endif
# ifndef OPENSSL_NO_STATIC_ENGINE
#  define OPENSSL_NO_STATIC_ENGINE
# endif


/* Generate 80386 code? */

/* For VC */
#if defined(_WIN64)
    #if !defined(OPENSSL_SYS_WIN64)
    # define OPENSSL_SYS_WIN64 1
    #endif
    #if !defined(OPENSSL_EXPORT_VAR_AS_FUNCTION)
    # define OPENSSL_EXPORT_VAR_AS_FUNCTION
    #endif
#elif defined(_WIN32)
    #if !defined(OPENSSL_SYS_WIN32)
    # define OPENSSL_SYS_WIN32 1
    #endif
    #if !defined(OPENSSL_EXPORT_VAR_AS_FUNCTION)
    # define OPENSSL_EXPORT_VAR_AS_FUNCTION
    #endif
#elif defined(__vxworks)
    #if !defined(OPENSSL_SYS_VXWORKS)
    # define OPENSSL_SYS_VXWORKS 1
    #endif
#endif

#if !defined(RC4_INT)
#if defined(_WIN32) || defined(_WIN64) || defined(__x86_64) || defined(__i386__)
    # define RC4_INT unsigned int
#else
    # define RC4_INT unsigned char
#endif
#endif

# undef BN_LLONG
# undef SIXTY_FOUR_BIT_LONG
# undef SIXTY_FOUR_BIT
# undef THIRTY_TWO_BIT

#if defined(_WIN64) || defined(__x86_64) || defined(__aarch64__) || defined(__ppc64__) || defined(__mips64) || \
    defined(__LP64__) || (defined(__SIZEOF_LONG__) && __SIZEOF_LONG__==8) || \
    (defined(__LONG_MAX__) && __LONG_MAX__==9223372036854775807LL) || \
    (defined(__SIZE_MAX__) && __SIZE_MAX__==18446744073709551615ULL)
    # define SIXTY_FOUR_BIT
#else
    # define BN_LLONG
    # define THIRTY_TWO_BIT
#endif

/*
 * The following are cipher-specific, but are part of the public API.
 */
#if defined(OPENSSL_SYS_UEFI)
# undef BN_LLONG
# undef SIXTY_FOUR_BIT_LONG
# undef SIXTY_FOUR_BIT
# undef THIRTY_TWO_BIT
#endif

# ifdef  __cplusplus
}
# endif

#endif                          /* OPENSSL_CONFIGURATION_H */
