/******************************************************************************

                  版权所有 (C), 2007-2008, 华为技术有限公司

******************************************************************************
  文 件 名   : ipmi_oem.h
  版 本 号   : 初稿
  作    者   :
  生成日期   : 2008年1月14日
  最近修改   :
  功能描述   : ipmi_oem.c 的头文件
  函数列表   :
  修改历史   :
  1.日    期   : 2008年1月14日
    作    者   :
    修改内容   : 创建文件

******************************************************************************/
#ifndef __IPMI_OEM_H__
#define __IPMI_OEM_H__

#define IPMI_HUAWEI_OEM_NETFN 0x30

#define IPMI_OEM_GET_MAC_ADDRESS 0x07
#define IPMI_OEM_GET_BLADE_VERSION 0x15
#define IPMI_OEM_GET_MAC_COUNT 0x16

#define IPMI_OEM_DFT_COMMAND 0x90
#define IPMI_OEM_CLI_COMMAND 0x91
#define IPMI_OEM_SYS_COMMAND 0x92
#define IPMI_OEM_INTERAL_COMMAND 0x93
#define IPMI_OEM_SHMC_COMMAND    0x94


//OEM{DFT:30 90}
#define IPMI_OEM_WRITE_MAC_ADDRESS 0x00
#define IPMI_OEM_READ_MAC_ADDRESS 0x01
#define IPMI_OEM_PHYSICAL_LED_TEST 0x02
#define IPMNI_OEM_CLEAR_FRU 0X03
#define IPMI_OEM_WRITE_ELABLE_DATA 0x04
#define IPMI_OEM_READ_ELABLE_DATA 0x05
#define IPMI_OEM_UPDATE_ELABLE_DATA 0x06
#define IPMI_OEM_READ_VERSION_DATA 0x08
#define IPMI_OEM_START_DEVICE_TEST 0x09
#define IPMI_OEM_GET_DEVICE_TEST_RESULT 0x0A
#define IPMI_OEM_START_IPMB_TEST 0x0C
#define IPMI_OEM_READ_VIDEO_DATA 0x10
#define IPMI_OEM_SET_SERIAL_PORT 0x12
#define IPMI_OEM_GET_HANDLE_STATE 0x13
#define IPMI_OEM_RESET_FRU 0x14
#define IPMI_OEM_SET_ETHERNET_MODE 0x15
#define IPMI_OEM_GET_ETHERNET_MODE 0x16
#define IPMI_OEM_ENABLE_DISABLE_DFT_COMMAND 0x20
#define IPMI_OEM_SET_GLOBAL_CONFIG 0x21
#define IPMI_OEM_GET_GLOBAL_CONFIG 0x22
#define IPMI_OEM_GET_LAN_CONFIG 0x24
#define IPMI_OEM_START_PORT_TEST 0x25
#define IPMI_OEM_GET_PORT_TEST_RESULT 0x26
#define IPMI_OEM_GENERATE_DEVICE_GUID 0x27
#define IPMI_OEM_SET_KEYBOARD_VALUE 0x28
#define IPMI_DFT_GET_COMPONENT_INFO 0x29
#define IPMI_DFT_GET_RELEASE_DATE 0x30
#define IPMI_DFT_GET_CHIP_STATUS  0x35
/*OEM{CLI:30 91}*/
#define IPMI_OEM_SET_FAN_MODE                  0x01
#define IPMI_OEM_GET_FAN_MODE                  0x02
#define IPMI_OEM_GET_COMPONENT_INFO_PROPERTIES 0x03
#define IPMI_OEM_GET_IP_MODE                   0x04
#define IPMI_OEM_FIX_IP                        0x05
#define IPMI_OEM_UPGRADE_COMPONENT             0x06
#define IPMI_OEM_GET_80_VAL                    0x07
#define IPMI_OEM_GET_BLADE_HEALTH              0x08
#define IPMI_OEM_GET_BLADE_HEALTH_EVENTS       0x09
#define IPMI_OEM_SET_MOTHERBOARD_SERIAL_NUMBER 0x0A
#define IPMI_OEM_GET_MOTHERBOARD_SERIAL_NUMBER 0x0B
#define IPMI_OEM_SET_SENSOR_TEST_VAL           0x0C
#define IPMI_OEM_STOP_HW_WATCHDOG              0x0D
#define IPMI_OEM_USER_AUTHENTICATION           0x11
#define IPMI_OEM_GET_COMPONENT_INFO            0x12
#define IPMI_OEM_GET_BAK_SEL                   0X14

#define IPMI_OEM_SET_ROLLBACK                0X15
#define IPMI_OEM_GET_ROLLBACKSTATUS          0X16

#define IPMI_OEM_SET_SERIAL_CONNECTION       0x17
#define IPMI_OEM_GET_SERIAL_CONNECTION       0x18
#define IPMI_OEM_SET_THIRD_SERIAL_CONNECTION 0x19
#define IPMI_OEM_GET_THIRD_SERIAL_CONNECTION 0x1A

/* BEGIN: Added by Qiurenyuan, 2011/11/16 10:13:50   问题单号:DTS2011111600670 */
#define IPMI_OEM_GET_LOCATION_ID   0x1B
#define IPMI_OEM_SET_LOCATION_ID   0x1C

#define IPMI_OEM_MAX_LOCATIOIN_SIZE  128

#define LOCATION_FILE     "/dev/shm/save/shutdown_file/location.conf"
/* END:   Added by Qiurenyuan, 2011/11/16 10:13:55 */

//OEM{SYS:30 92}
#define IPMI_OEM_SET_TCK                0x01
#define IPMI_OEM_SET_BIOS_VERSION       0x02
#define IPMI_OEM_SET_UPDATE_BIOS_STATUS 0x03
#define IPMI_OEM_SET_SMBIOS_DATA        0x04
/* BEGIN: Modified by maoali, 2011/12/5   PN:R2C02_BIOS_Alert*/
#define IPMI_OEM_SET_DEVICE_STATUS      0x05
#define IPMI_OEM_GET_DEVICE_STATUS      0x06
/* END:   Modified by maoali, 2011/12/5 */


/* BEGIN: Modified by huang, 2011/10/29, HBA卡管理 */
#define IPMI_OEM_SET_HBA_CONFIG     0x07
#define IPMI_OEM_GET_HBA_CONFIG     0x08
/* END:   Modified by huang, 2011/10/29, HBA卡管理  */
/* BIOS向BMC写数据 */
#define IPMI_OEM_WRITE_FILE_TO_BMC      0x09
/* BIOS从BMC读数据 */
#define IPMI_OEM_READ_FILE_FROM_BMC     0x0A
/* 设置option.ini */
#define IPMI_OEM_SET_FILE_CHANGEED      0x0B
/* 获取option.ini */
#define IPMI_OEM_GET_FILE_CHANGED       0x0C
//CPU计数
/* BEGIN: Added by Qiurenyuan, 2011/11/16 10:20:29   问题单号:DTS2011111503436  */
#define IPMI_OEM_GET_CPU_READING    0x0D
#define IPMI_GET_MAX_CPU_TEMP             0xFF
#define IPMI_MAX_CPU_NUM                  4
#define IPMI_CPU_ABSEBT                   0xff
/* END:   Added by Qiurenyuan, 2011/11/16 10:20:32 */
/* BEGIN: Modified by h00164462, 2012/4/23, PN:BIOS Syslog */
#define IPMI_OEM_ADD_SYSLOG_ENTRY         0x0F
/* END:   Modified by h00164462, 2012/4/23, PN:BIOS Syslog */

/* BEGIN: Modified by y00208094, 2012/5/30 */
#define IPMI_OEM_GET_RESTART_CAUSE       0x11
/* END:  Modified by y00208094, 2012/5/30 */
#define IPMI_OEM_SET_UPGRADE_ROM_SKU_NUMBER  0x12

//OEM{INTERAL:30 93}
#define IPMI_OEM_SEND_TRAP_EVENT     0x01
#define IPMI_OEM_GET_SENSOR_NAME     0x02
#define IPMI_OEM_GET_SCREEN_SNAPSHOT 0x03
#define IPMI_OEM_SET_AUTH_KEY 0x04
#define IPMI_OEM_SET_CONFIGURATION 0x05
#define IPMI_OEM_GET_CONFIGURATION 0x06
#define IPMI_OEM_SET_RECOVER_POINT 0x07
#define IPMI_OEM_RECOVER_ACTION 0x08
#define IPMI_OEM_GET_MAX_SEVERITY 0x09
#define IPMI_OEM_GET_SMBIOS_INFO 0x0A
#define IPMI_OEM_SET_WEB_AUTH_CODE 0x0B
#define IPMI_OEM_GET_USER_GROUP 0x0C
#define IPMI_OEM_SET_USER_GROUP 0x0D
#define IPMI_OEM_SET_FAN_SPEED 0x0E
#define IPMI_OEM_SET_SERVICE_CONFIGURATION   0x0F
#define IPMI_OEM_GET_SERVICE_CONFIGURATION   0x10

#define IPMI_OEM_GET_POWER_STATISTIC        0x11
#define IPMI_OEM_SET_POWER_STATISTIC_CLEAR  0x12
#define IPMI_OEM_SET_POWER_CAPPING          0x13
#define IPMI_OEM_GET_POWER_CAPPING_INFO     0x14
#define IPMI_OEM_GET_KINESCOPE_TRIGGER  0x18
#define IPMI_OEM_SET_KINESCOPE_TRIGGER  0x19


#define IPMI_OEM_GET_PASS_COMPLEXITY_CONFIG       0x21
#define IPMI_OEM_SET_PASS_COMPLEXITY_CONFIG       0x22
#define IPMI_OEM_GET_UPGRADE_ROM_SKU_NUMBER   0x23


#define IPMI_OEM_GET_POWER_SUPPLY_INFO      0x1E

#define IPMI_OEM_GET_POWER_STATISTIC_POWERREADING   0x0
#define IPMI_OEM_GET_POWER_STATISTIC_PEAK           0x1
#define IPMI_OEM_GET_POWER_STATISTIC_AVERAGE        0x2
#define IPMI_OEM_GET_POWER_STATISTIC_CONSUMPTION    0x3


#define IPMI_OEM_GET_SOL_BLACKBOX_DATA      0x1F  //SOL Black_box 数据下载
#define IPMI_OEM_GET_SOL_DEST_NUM      0x0d
#define IPMI_OEM_GET_SOL_DEST_NAME      0x0e

#define SOL_BLACKBOX_COLLECT_CMD   0x00
#define SOL_BLACKBOX_QUERY_CMD     0x01

#define IPMI_OEM_GET_USER_WEB_LOGIN 0x24


#define IPMI_OEM_SET_ALERT_CONFIGURATION 0x15
#define IPMI_OEM_GET_ALERT_CONFIGURATION 0x16

//ALERT CONFIGURATION
#define ALERT_CONFIGURATION_FORMAT_SEPARATOR         0x01
#define ALERT_CONFIGURATION_FORMAT_INCLUDE_KEYWORD   0x02
#define ALERT_CONFIGURATION_FORMAT_KEYWORD_STRING    0x03
#define ALERT_CONFIGURATION_TRAP_PROTOCOL            0x04
#define ALERT_CONFIGURATION_TRAP_DEST_TEST           0x05
#define ALERT_CONFIGURATION_EMAIL_DESTINATION_ENABLE 0x06
#define ALERT_CONFIGURATION_EMAIL_ADDRESS            0x07
#define ALERT_CONFIGURATION_EMAIL_DESCRIPTION        0x08
#define ALERT_CONFIGURATION_SMTP_DEST_TEST           0x09
#define ALERT_CONFIGURATION_EMAIL_TEMPLET_TOPIC      0x0A
#define ALERT_CONFIGURATION_EMAIL_TEMPLET_FROM       0x0B
#define ALERT_CONFIGURATION_EMAIL_TEMPLET_EXTRA      0x0C
#define ALERT_CONFIGURATION_SMTP_LOGIN_MODE          0x0D
#define ALERT_CONFIGURATION_SMTP_LOGIN_USERNAME      0x0E
#define ALERT_CONFIGURATION_SMTP_LOGIN_PASSWD        0x0F
#define ALERT_CONFIGURATION_EMAIL_DESTINATION_COUNTS 0x10
//end

//OEM{SHMC:30 94}
#define IPMI_OEM_UPLOAD_RESOURCE     0x05
#define IPMI_OEM_DOWNLOAD_RESOURCE   0x06
#define IPMI_OEM_SET_CHASSIS_NUM     0x07    // 设置机框号
#define IPMI_OEM_GET_CHASSIS_NUM     0x08    // 查询机框号
#define IPMI_OEM_GET_SUPPORT         0x09
#define IPMI_OEM_GET_SPAN_SLOT_MAP   0x0A
#define IPMI_OEM_GET_DEBUG_INFO      0x0c    // 一键收集命令
#define IPMI_OEM_SET_DEVICE_GUID     0x11
#define IPMI_OEM_SET_DISK_POWER_STATE  0x13
#define IPMI_OEM_GET_COOLING_POLICY_RECORD 0x17
#define IPMI_OEM_GET_COOLING_POLICY_STATE 0x19

#endif /* __IPMI_OEM_H__ */
