/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Description: bmc_global模块的类属性和方法描述文件
 * Author: g00610211
 * Create: 2022-08-22
 */
#ifndef PME_PROPERTY_METHOD_BMC_GLOBAL_H
#define PME_PROPERTY_METHOD_BMC_GLOBAL_H

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

/***CAServerCACert类***/
#define CLASS_CA_SERVER_CACERT "CAServerCACert"
#define CA_SERVER_CACERT_METHOD_IMPORT_CACERT "ImportCA"
#define CA_SERVER_CACERT_METHOD_IMPORT_CRL "ImportCRL"
#define CA_SERVER_CACERT_METHOD_DELETE_CRL "DeleteCRL"
#define PROPERTY_CA_SERVER_CACERT_SN "SerialNumber"
#define PROPERTY_CA_SERVER_CACERT_ISSUEBY "IssueBy"
#define PROPERTY_CA_SERVER_CACERT_ISSUETO "IssueTo"
#define PROPERTY_CA_SERVER_CACERT_ISSUEBYCN "IssueByCN"
#define PROPERTY_CA_SERVER_CACERT_ISSUETOCN "IssueToCN"
#define PROPERTY_CA_SERVER_CACERT_VALIDFROM "ValidFrom"
#define PROPERTY_CA_SERVER_CACERT_VALIDTO "ValidTo"
#define PROPERTY_CA_SERVER_CACERT_CRL_FILEPATH "CRLFilePath"
#define PROPERTY_CA_SERVER_CACERT_SIGALGORITHM "SigAlgorithm"
#define PROPERTY_CA_SERVER_CACERT_KEYLENGTH "KeyLength"
#define PROPERTY_CA_SERVER_CACERT_KEYUSAGE "KeyUsage"
#define PROPERTY_CA_SERVER_CACERT_CRL_STARTTIME "CRLStartTime"
#define PROPERTY_CA_SERVER_CACERT_CRL_EXPIRETIME "CRLExpireTime"
#define PROPERTY_CA_SERVER_CACERT_FINGERPRINT "FingerPrint"

/***CAServerClientCert类***/
#define CLASS_CA_SERVER_CLIENTCERT "CAServerClientCert"
#define CA_SERVER_CLIENTCERT_METHOD_IMPORT_CLIENTCERT "ImportClientCert"
#define PROPERTY_CA_SERVER_CLIENTCERT_ISSUEBY "IssueBy"
#define PROPERTY_CA_SERVER_CLIENTCERT_ISSUETO "IssueTo"
#define PROPERTY_CA_SERVER_CLIENTCERT_ISSUEBYCN "IssueByCN"
#define PROPERTY_CA_SERVER_CLIENTCERT_ISSUETOCN "IssueToCN"
#define PROPERTY_CA_SERVER_CLIENTCERT_VALIDFROM "ValidFrom"
#define PROPERTY_CA_SERVER_CLIENTCERT_VALIDTO "ValidTo"
#define PROPERTY_CA_SERVER_CLIENTCERT_SN "SerialNumber"
#define PROPERTY_CA_SERVER_CLIENTCERT_SIGALGORITHM "SigAlgorithm"
#define PROPERTY_CA_SERVER_CLIENTCERT_KEYLENGTH "KeyLength"
#define PROPERTY_CA_SERVER_CLIENTCERT_KEYUSAGE "KeyUsage"
#define PROPERTY_CA_SERVER_CLIENTCERT_FINGERPRINT "FingerPrint"

#define CLASS_HTTPS_SERVER_ROOTCERT "RemoteHttpsServerRootCert"
#define HTTPS_SERVER_ROOTCERT_METHOD_IMPORT_ROOTCERT "ImportRootCert"
#define HTTPS_SERVER_ROOTCERT_METHOD_IMPORT_CRL "ImportCRL"
#define HTTPS_SERVER_ROOTCERT_METHOD_DELETE_CRL "DeleteCRL"
#define HTTPS_SERVER_ROOTCERT_METHOD_DELETE_ROOTCERT "DeleteRootCert"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_ID "CertId"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_USAGE  "Usage"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_SN "SerialNumber"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_ISSUEBY "IssueBy"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_ISSUETO "IssueTo"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_ISSUEBYCN "IssueByCN"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_ISSUETOCN "IssueToCN"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_VALIDFROM "ValidFrom"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_VALIDTO "ValidTo"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_CRL_FILEPATH "CRLFilePath"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_SIGALGORITHM "SigAlgorithm"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_KEYLENGTH "KeyLength"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_KEYUSAGE "KeyUsage"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_CRL_STARTTIME "CRLStartTime"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_CRL_EXPIRETIME "CRLExpireTime"
#define PROPERTY_HTTPS_SERVER_ROOTCERT_FINGERPRINT "FingerPrint"

#define CLASS_NAME_CMP_CONFIG                     "CMPConfig"
#define PROPERTY_CMPCFG_CASERVER_ADDR             "CAServerAddr"
#define PROPERTY_CMPCFG_CASERVER_PORT             "CAServerPort"
#define PROPERTY_CMPCFG_CASERVER_CMPPATH          "CAServerCMPPath"
#define PROPERTY_CMPCFG_TLSAUTHTYPE               "TLSAuthType"
#define PROPERTY_CMPCFG_AUTOUPENABLED             "AutoUpdateEnabled"
#define PROPERTY_CMPCFG_COUNTRY                   "Country"
#define PROPERTY_CMPCFG_STATE                     "State"
#define PROPERTY_CMPCFG_LOCATION                  "Location"
#define PROPERTY_CMPCFG_ORGNAME                   "OrgName"
#define PROPERTY_CMPCFG_ORGUNIT                   "OrgUnit"
#define PROPERTY_CMPCFG_COMMONNAME                "CommonName"
#define PROPERTY_CMPCFG_INTERALNAME               "InternalName"
#define PROPERTY_CMPCFG_EMAIL                     "Email"
#define METHOD_SET_CMPCFG_CASERVER_ADDR           "SetCMPCfgCAServerAddr"
#define METHOD_SET_CMPCFG_CASERVER_PORT           "SetCMPCfgCAServerPort"
#define METHOD_SET_CMPCFG_CASERVER_CMPPATH        "SetCMPCfgCAServerCMPPath"
#define METHOD_SET_CMPCFG_TLS_AUTHTYPE            "SetCMPCfgTLSAuthType"
#define METHOD_SET_CMPCFG_AUTOUPDATE_ENABLED      "SetCMPCfgAutoUpdateEnabled"
#define METHOD_SET_CMPCFG_SUBJECTINFO             "SetCMPCfgSubjectInfo"
#define METHOD_ACT_CERT_UPDATE                    "UpdateCertFromCA"

#define CLASS_BBU_MODULE_NAME                  "BBUModule"
#define PROPERTY_BBU_MODULE_ID                 "Id"
#define PROPERTY_BBU_MODULE_BOARDNAME          "BoardName"
#define PROPERTY_BBU_MODULE_PRESENCE           "Presence"
#define PROPERTY_BBU_MODULE_HEALTH             "Health"
#define PROPERTY_BBU_MODULE_PROTOCOL           "Protocol"
#define PROPERTY_BBU_MODULE_TEST_STATUS        "TestStatus"
#define PROPERTY_BBU_MODULE_COMMUNICATION_LOST "CommunicationLost"
#define PROPERTY_BBU_MODULE_REFCHIP            "RefChip"
#define PROPERTY_BBU_MODULE_ALARM_CODE         "AlarmCode"
#define PROPERTY_BBU_MODULE_ALM_THRESHOLD      "AlarmThreshold"
#define PROPERTY_BBU_MODULE_CAP_ALARM          "CapAlarm"
#define PROPERTY_BBU_MODULE_WORK_STATUS        "WorkStatus"
#define PROPERTY_BBU_MODULE_TEMP1              "Temperature1"
#define PROPERTY_BBU_MODULE_TEMP2              "Temperature2"
#define PROPERTY_BBU_MODULE_TEMP3              "Temperature3"
#define PROPERTY_BBU_MODULE_TEMP4              "Temperature4"
#define PROPERTY_BBU_MODULE_TEMP5              "Temperature5"
#define PROPERTY_BBU_MODULE_TEMP6              "Temperature6"
#define PROPERTY_BBU_MODULE_TEMP7              "Temperature7"
#define PROPERTY_BBU_MODULE_VOLTAGE1           "Voltage1"
#define PROPERTY_BBU_MODULE_VOLTAGE2           "Voltage2"
#define PROPERTY_BBU_MODULE_VOLTAGE3           "Voltage3"
#define PROPERTY_BBU_MODULE_VOLTAGE4           "Voltage4"
#define PROPERTY_BBU_MODULE_VOLTAGE5           "Voltage5"
#define PROPERTY_BBU_MODULE_VOLTAGE6           "Voltage6"
#define PROPERTY_BBU_MODULE_CURRENT1           "Current1"
#define PROPERTY_BBU_MODULE_CURRENT2           "Current2"
#define PROPERTY_BBU_MODULE_CURRENT3           "Current3"
#define PROPERTY_BBU_MODULE_CURRENT4           "Current4"
#define PROPERTY_BBU_MODULE_CURRENT5           "Current5"
#define PROPERTY_BBU_MODULE_M2_STATUS          "M2Presence"
#define PROPERTY_BBU_MODULE_INSTANT_CAP        "InstantCap"
#define PROPERTY_BBU_MODULE_STABLE_CAP         "StableCap"
#define PROPERTY_BBU_MODULE_REMAIN_CAP         "RemainCap"
#define PROPERTY_BBU_MODULE_PER_REMAIN_CAP     "PerRemCap"
#define PROPERTY_BBU_MODULE_CELL_MAX_TEMP      "CellMaxTemperature"
#define PROPERTY_BBU_MODULE_CELL_MIN_TEMP      "CellMinTemperature"
#define PROPERTY_BBU_MODULE_DISCHARGE_CURRENT_LIMIT      "DischargeCurrentLimit"
#define PROPERTY_BBU_MODULE_OUTPUT_POWER        "PowerOut"
#define PROPERTY_BBU_MODULE_RATE_POWER         "RatePower"
#define PROPERTY_BBU_MODULE_FULL_CAP            "FullCap"
#define PROPERTY_BBU_MODULE_BBU_TYPE           "BBUType"
#define PROPERTY_BBU_MODULE_PCB_VER            "PcbId"
#define PROPERTY_BBU_MODULE_FIRMWARE_VER       "FirmwareVersion"
#define PROPERTY_BBU_MODULE_SN                 "SN"
#define PROPERTY_BBU_MODULE_BATT_MODEL         "BattModel"
#define PROPERTY_BBU_MODULE_BATT_SN            "BattSN"
#define PROPERTY_BBU_MODULE_LOCATION           "Location"
#define PROPERTY_BBU_MODULE_DEVICE_NAME        "DeviceName"
/* BEGIN : Added by zwx536747, 2020/02/27,UADP509211 */
#define PROPERTY_BBU_MODULE_BATT_PARTNUM       "BattPartNum"
/* END   : Added by zwx536747, 2016/02/27,UADP509211 */
#define PROPERTY_BBU_MODULE_BATT_MANU          "BattManu"
#define PROPERTY_BBU_MODULE_BATT_MANU_DATE     "BattManuDate"
#define PROPERTY_BBU_MODULE_WORK_TIME          "WorkTime"
#define PROPERTY_BBU_MODULE_DISCHARGE_TIMES          "DischargeTimes"
#define PROPERTY_BBU_MODULE_BATT_DISCHARGE_TIMES    "BattDischargeTimes"
#define PROPERTY_BBU_MODULE_BATT_SILK_TEXT          "SilkText"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE1           "CellVoltage1"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE2           "CellVoltage2"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE3           "CellVoltage3"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE4           "CellVoltage4"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE5           "CellVoltage5"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE6           "CellVoltage6"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE7           "CellVoltage7"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE8           "CellVoltage8"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE9           "CellVoltage9"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE10          "CellVoltage10"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE11          "CellVoltage11"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE12          "CellVoltage12"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE13          "CellVoltage13"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE14          "CellVoltage14"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE15          "CellVoltage15"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE16          "CellVoltage16"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE17          "CellVoltage17"
#define PROPERTY_BBU_MODULE_CELL_VOLTAGE18          "CellVoltage18"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE1       "CellTemperature1"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE2       "CellTemperature2"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE3       "CellTemperature3"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE4       "CellTemperature4"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE5       "CellTemperature5"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE6       "CellTemperature6"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE7       "CellTemperature7"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE8       "CellTemperature8"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE9       "CellTemperature9"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE10      "CellTemperature10"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE11      "CellTemperature11"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE12      "CellTemperature12"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE13      "CellTemperature13"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE14      "CellTemperature14"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE15      "CellTemperature15"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE16      "CellTemperature16"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE17      "CellTemperature17"
#define PROPERTY_BBU_MODULE_CELL_TEMPERATURE18      "CellTemperature18"
#define PROPERTY_BBU_MODULE_STOP_STDBY              "StopStdby"
#define PROPERTY_BBU_MODULE_STDBY_STATUS            "StdbyStatus"
#define PROPERTY_BBU_MODULE_CPLD_ALARM              "CpldAlarm"
#define PROPERTY_BBU_MODULE_CHARGE_STATUS           "ChargeStatus"
#define PROPERTY_BBU_MODULE_UPGRADE_STATUS          "UpgradeStatus"
#define PROPERTY_BBU_MODULE_STATE_OF_HEALTH         "StateOfHealth"
#define PROPERTY_BBU_MODULE_BATT_PART_NUM           "BattPartNum"
#define PROPERTY_BBU_MODULE_RATE_CAP                "RateCap"
#define PROPERTY_BBU_MODULE_MAX_CHARGE_CURRENT      "MaxChargeCurrent"
#define PROPERTY_BBU_MODULE_REAL_CHARGE_CURRENT     "RealChargeCurrent"
#define PROPERTY_BBU_MODULE_REAL_VOLTAGE            "RealVoltage"
#define PROPERTY_BBU_MODULE_ALARM_STATUS_EX         "AlarmStatusEx"
#define PROPERTY_BBU_MODULE_BACKUP_CAP_ALARM_STATUS "BackupCapAlarmStatus"
#define PROPERTY_BBU_MODULE_DIRE_SAMPL_VOLTAGE "DirectSamplingVoltage"
#define PROPERTY_BBU_MODULE_BATTERY_CURR_SAMPL "BatteryCurrentSampling"
#define PROPERTY_BBU_MODULE_DISCHARGING_STATUS "DischargingStatus"
#define PROPERTY_BBU_MODULE_BATTERY_STRING_CURRENT "BatteryStringCurrent"
#define PROPERTY_BBU_MODULE_CELL_TEMP_IN_RANGE_1_TIME "CellTempInRange1Time"
#define PROPERTY_BBU_MODULE_BAT_ABILITY_COEF "BatAbilityCoefficients"
#define PROPERTY_BBU_MODULE_INSTANT_CAP             "InstantCap"
#define PROPERTY_BBU_MODULE_STABLE_CAP              "StableCap"
#define PROPERTY_BBU_MODULE_POWER_OFF_SCAN_DISABLE  "PowerOffScanDisable"
#define PROPERTY_BBU_MODULE_OPERATE_DISCHARGE       "OperateDischarge"
#define PROPERTY_BBU_MODULE_DELAY_KILL_BBU_EN       "DelayKillBbuEn"       /* 延时关闭BBU使能 */
#define PROPERTY_BBU_MODULE_POWER_TYPE              "PowerType"
#define PROPERTY_BBU_MODULE_LOG_REALTIME_ENABLE     "LogRealtimeEnable"
#define PROPERTY_BBU_MODULE_LAST_DISCHARGE_TIME     "LastDischargeTime"
#define PROPERTY_BBU_MODULE_CHARGE_MODE             "ChargeMode"
#define PROPERTY_BBU_MODULE_CHARGE_TYPE             "ChargeType"
#define PROPERTY_BBU_MODULE_MIRROR_NODE_STATUS      "MirrorNodeStatus"
#define PROPERTY_BBU_MODULE_ONLINE_TEST_ENABLE      "OnlineTestEnable"
#define PROPERTY_BBU_MODULE_ONLINE_TEST_START_CON   "OnlineTestStartCon"
#define PROPERTY_BBU_MODULE_ONLINE_TEST_STOP_CON    "OnlineTestStopCon"
#define PROPERTY_BBU_MODULE_ONLINE_TEST_START_CON_FUNC "OnlineTestStartConFunc"
#define PROPERTY_BBU_MODULE_ONLINE_TEST_STOP_CON_FUNC "OnlineTestStopConFunc"
#define PROPERTY_BBU_MODULE_PCB_VERSION               "PcbVersion"
#define PROPERTY_BBU_MODULE_WORK_MODE                 "WorkMode"

#define METHOD_BBU_MODULE_SET_UPGRADE_STATUS        "SetUpgradeStatus"
#define METHOD_BBU_MODULE_STOP_STDBY_STATUS         "StopStdbyStatus"
#define METHOD_BBU_MODULE_OPERATE_BBU               "OperateBbu"
#define METHOD_BBU_MODULE_GET_ELABEL                "GetBbuElabel"
#define METHOD_BBU_MODULE_SET_ELABEL                "SetBbuElabel"
#define METHOD_BBU_MODULE_SET_BBU_LOG_NUM           "SetBbuLogNum"

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* PME_PROPERTY_METHOD_BMC_GLOBAL_H */