/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2009-2019. All rights reserved.
 * Description  : CMP context APIs
 * Author       : Arun Raj
 * Create       : 14-10-2009
 * FileName     : ipsi_cmp_errordef.h\
 * Version      : 1
 * Function List: None
 * <author>   <date>          <desc>
 */
#ifndef IPSI_CMP_ERRORDEF_H
#define IPSI_CMP_ERRORDEF_H

#ifdef __cplusplus
extern "C" {
#endif

#define IPSI_CMP_ERR_RANGE 200

#define IPSI_CMP_ERR_INIT 40000

// System Error: Include mem allocation failure,socket  closed ,
// file open error......
#define IPSI_CMP_ERR_SYSTEM_INIT (IPSI_CMP_ERR_INIT + 1)

// MAX Total System error limit
#define IPSI_CMP_ERR_SYSTEM_LIMIT (IPSI_CMP_ERR_SYSTEM_INIT + IPSI_CMP_ERR_RANGE - 1)

#define IPSI_CMP_ERR_COMMON_INIT (IPSI_CMP_ERR_SYSTEM_LIMIT + 1)

// MAX Total Common error limit
#define IPSI_CMP_ERR_COMMON_LIMIT (IPSI_CMP_ERR_COMMON_INIT + IPSI_CMP_ERR_RANGE - 1)

#define IPSI_CMP_ERR_HTTP_INIT (IPSI_CMP_ERR_COMMON_LIMIT + 1)

// MAX Total Http error limit
#define IPSI_CMP_ERR_HTTP_LIMIT (IPSI_CMP_ERR_HTTP_INIT + IPSI_CMP_ERR_RANGE - 1)

/**
 * @ingroup  CMPv2
 *
 * enum IPSI_CMP_system_errors name is not required
 */
enum {
    IPSI_CMP_ERR_MALLOC_FAILED = IPSI_CMP_ERR_SYSTEM_INIT,
    IPSI_CMP_ERR_MULTITHREAD_FAILED,
    IPSI_CMP_ERR_SSCANF_FAILED,
    IPSI_CMP_ERR_GET_SYS_TIME_FAILED,
    IPSI_CMP_ERR_MEMSET_FAILED,
    IPSI_CMP_ERR_MEMCPY_FAILED,
    IPSI_CMP_ERR_STRCPY_FAILED,
    IPSI_CMP_ERR_STRCAT_FAILED,

    // Please add all error between init and max
    IPSI_CMP_ERR_SYSTEM_MAX
};

/**
 * @ingroup  CMPv2
 *
 * enum to  hold the context and object errors
 * enum IPSI_CMP_system_errors name is not required
 */
enum {
    // Invalid arguments
    IPSI_CMP_ERR_INVALID_ARGS = IPSI_CMP_ERR_COMMON_INIT,
    IPSI_CMP_ERR_DUP_GENNAME_FAILED,
    IPSI_CMP_ERR_GENNAME_NOT_SET,
    IPSI_CMP_ERR_INVALID_LIB_FINI,
    IPSI_CMP_ERR_PKI_OBJ_NOT_SET,
    IPSI_CMP_ERR_TRANS_METHOD_NOT_SET,
    IPSI_CMP_ERR_SENDER_OR_RECIP_NAME_NOT_SET,
    IPSI_CMP_ERR_CERT_CONF_CB_NOT_SET,
    IPSI_CMP_ERR_CMP_HEADER_CREATION_FAILED,
    IPSI_CMP_ERR_PKCS10_MSG_DECODE_FAILED,
    IPSI_CMP_ERR_CMP_MSG_CREATION_FAILED,
    IPSI_CMP_ERR_GETTING_IDENTITY_CERT_CHAIN_FAILED,
    IPSI_CMP_ERR_GETTING_PRIV_KEY_FOR_CERT_FAILED,
    IPSI_CMP_ERR_CMP_NOT_RSA_FOR_PROT,
    IPSI_CMP_ERR_CMP_PROT_GEN_FAILED,
    IPSI_CMP_ERR_CMP_MSG_ENCODE_FAILED,
    IPSI_CMP_ERR_CMP_MSG_SEND_FAILED,
    IPSI_CMP_ERR_PROT_ALG_IN_RESP_IS_INVALID,
    IPSI_CMP_ERR_GET_EXTRA_CERTS_FAILED,
    IPSI_CMP_ERR_CERT_PATH_VALIDATION_FAILED,
    IPSI_CMP_ERR_PUB_KEY_EXTRACT_FAILED,
    IPSI_CMP_ERR_SIGNATURE_VAL_FAILED,
    IPSI_CMP_ERR_UNABLE_TO_GET_HDR_FROM_RESP,
    IPSI_CMP_ERR_INCORRECT_TRANS_ID,
    IPSI_CMP_ERR_INCORRECT_NONCE,
    IPSI_CMP_ERR_PROTECTION_VAL_FAILED,
    IPSI_CMP_ERR_GET_RESP_FAILED,
    IPSI_CMP_ERR_DECODE_RESP_MSG_FAILED,
    IPSI_CMP_ERR_GETTING_CMP_BODY_FAILED,
    IPSI_CMP_ERR_RECEIVED_ERROR_FROM_CERT_CONF_CB,
    IPSI_CMP_ERR_RECEIVED_ERROR_RESPONSE_MSG,
    IPSI_CMP_ERR_UNEXPECTED_RESPONSE_MSG_TYPE,
    IPSI_CMP_ERR_CMP_MESSAGE_BODY_CREATION_FAILED,
    IPSI_CMP_ERR_UNSUPPORTED_VERSION,
    IPSI_CMP_ERR_MSG_WITHOUT_PROT,
    IPSI_CMP_ERR_INVALID_PROT_BITS,
    IPSI_CMP_ERR_RECEIVED_INVALID_CERT_RESP,
    IPSI_CMP_ERR_INVALID_CERT_REQUEST_ID,
    IPSI_CMP_ERR_CA_CERT_NOT_SET,
    IPSI_CMP_ERR_INVALID_STORE_ARRAY_LENGTH,
    IPSI_CMP_ERR_NO_RESP,
    IPSI_CMP_ERR_CREATE_STATUS_INFO_FAILED,
    IPSI_CMP_ERR_RESP_MSG_NOT_CLEARED,
    IPSI_CMP_ERR_CERT_NOT_AVAILABLE,

    IPSI_CMP_ERR_CA_LIST_EMPTY,
    IPSI_CMP_ERR_EXTRA_CERT_LIST_EMPTY,
    IPSI_CMP_ERR_CMP_STORE_EMPTY,
    IPSI_CMP_ERR_CERT_REQ_REJECTED,
    IPSI_CMP_ERR_CRMF_MSG_DECODE_FAILED,
    IPSI_CMP_ERR_BAD_PACKET,
    IPSI_CMP_ERR_NO_REQ_PEND,
    IPSI_CMP_ERR_POLL_TIME_NOT_EXPIRED,
    IPSI_CMP_ERR_NO_CERT_ID_PRESENT,
    IPSI_CMP_ERR_NO_CERT_ID_MATCHED,
    IPSI_CMP_ERR_POLL_REQ_CREATE_FAILED,
    IPSI_CMP_ERR_ADD_POLL_REQ_FAILED,
    IPSI_CMP_ERR_NO_ERR_MSG,
    IPSI_CMP_ERR_DATE_COMPARE_FAILED,
    IPSI_CMP_ERR_UNABLE_TO_GET_CERT_FOR_PROT_VAL,
    IPSI_CMP_ERR_CONF_WAIT_NOT_AVAILABLE,
    IPSI_CMP_ERR_RECV_ENC_CERT,
    IPSI_CMP_COND_VAR_CREAT_FAIL,
    IPSI_CMP_ERR_CA_CERT_PATH_VALIDATION_FAILED,
    IPSI_CMP_ERR_REQ_MORE_THAN_TWO_CERT,
    IPSI_CMP_ERR_INVALID_TRANS_ID,
    IPSI_CMP_ERR_RECV_WRONG_RECIPIENT_NAME,
    IPSI_CMP_ERR_RECV_WRONG_SENDER_NAME,
    IPSI_CMP_ERR_RANDOM_NONCE_GEN_FAILED,
    IPSI_CMP_ERR_RANDOM_TRANS_ID_GEN_FAILED,
    IPSI_CMP_ERR_CRYPT_RANDOM_FAILED,
    IPSI_CMP_ERR_PASS_SENDER_KID_NOT_SET,
    IPSI_CMP_ERR_PBM_PARA_NOT_AVAILABLE,
    IPSI_CMP_ERR_UNKNOWN_ALG,
    IPSI_CMP_ERR_GEN_HMAC_PROT_FAILED,
    IPSI_CMP_ERR_MAC_VERIFICATION_FAILED,
    IPSI_CMP_ERR_DIGEST_CALC_FAILED,
    IPSI_CMP_ERR_SALT_CREAT_FAILED,
    IPSI_CMP_ERR_MAC_ALGID_CREAT_FAILED,
    IPSI_CMP_ERR_OWF_ALGID_CREAT_FAILED,
    IPSI_CMP_ERR_GEN_MAC_PROT_FAILED,
    IPSI_CMP_ERR_DUPING_MSG_PBM_PARA_FAILED,
    IPSI_CMP_ERR_DUPING_CTX_PBM_PARA_FAILED,
    IPSI_CMP_ERR_DUP_GENERAL_NAME_FAILED,
    IPSI_CMP_ERR_INVALID_ALGID_IN_CTX,
    IPSI_CMP_ERR_RCVD_WAIT_IN_PSK,
    IPSI_CMP_ERR_RCVD_TOO_LARGE_PBM_PARA,
    IPSI_CMP_ERR_INVALID_IP_TYPE,
    IPSI_CMP_ERR_INVALID_IP_ADDR,
    IPSI_CMP_ERR_SIGN_CB_FAILED,
    IPSI_CMP_ERR_PARSE_CONFIRMWAITTIME_FAILED,
    IPSI_CMP_ERR_GET_ENCRYPTED_PRIVKEY_FAILED,
    IPSI_CMP_ERR_COMMON_MAX
};

/**
 * @ingroup  CMPv2
 *
 * enum to hold the cmp errors
 */
enum {
    // xcap errors
    IPSI_CMP_REQ_ERR_CONNECTION_CLOSE = IPSI_CMP_ERR_HTTP_INIT,
    IPSI_CMP_REQ_ERR_WAIT_APP_RESPONSE_TIME_OUT,
    IPSI_CMP_REQ_ERR_ENCODE_RESP_FAILURE,
    IPSI_CMP_REQ_ERR_ENCODE_REQ_FAILURE,
    IPSI_CMP_REQ_ERR_CREATE_CONNECTION_FAILURE,
    IPSI_CMP_REQ_ERR_SEND_REQ_FAILURE,
    IPSI_CMP_REQ_ERR_DECODE_RESP_FAILURE,

    IPSI_CMP_REQ_ERR__REQ_TIMEOUT,
    IPSI_CMP_REQ_ERR_PIPELINE_USER_CLOSE,

    IPSI_CMP_REQ_ERR_TLS_UPGRADE_FAILURE,
    IPSI_CMP_REQ_ERR_REPORT_RESPONSE_FAILURE,

    // http errors
    IPSI_CMP_ERR_HTTP_ALREADY_INIT,
    IPSI_CMP_ERR_HTTP_HANDLE_CREATE_FAILED,
    IPSI_CMP_ERR_HTTP_INIT_FAILED,
    IPSI_CMP_ERR_SERVER_URI_LENGTH_TOO_LARGE,
    IPSI_CMP_ERR_VERSION_NOT_SUPPORTED,
    IPSI_CMP_ERR_REG_SYS_FUNC_FAILED,
    IPSI_CMP_ERR_REG_DEBUG_FUNC_FAILED,
    IPSI_CMP_ERR_SER_IP_NOT_SET,
    IPSI_CMP_ERR_SER_PORT_NOT_SET,
    IPSI_CMP_ERR_SER_URI_NOT_SET,
    IPSI_CMP_ERR_SER_VER_NOT_SET,
    IPSI_CMP_ERR_EXRCT_BODY_FROM_PACKET_FAILED,
    IPSI_CMP_ERR_EXRCT_STATUS_FROM_PACKET_FAILED,
    IPSI_CMP_ERR_CLON_MSG_FROM_HTTP_FAILED,
    IPSI_CMP_ERR_ADD_HANDLE_TO_LIST_FAILED,
    IPSI_CMP_ERR_STATUS_CODE_IS_NOT_OK,
    IPSI_CMP_ERR_UNABLE_TO_FIND_HTPP_METHOD,

    IPSI_CMP_ERR_ADD_HEADER_HOST_FAILED,
    IPSI_CMP_ERR_ADD_HEADER_CONTENT_FAILED,
    IPSI_CMP_ERR_ADD_HEADER_PRAGMA_FAILED,
    IPSI_CMP_ERR_ADD_HEADER_CACHE_FAILED,
    IPSI_CMP_ERR_ADD_HEADER_CONN_FAILED,
    IPSI_CMP_ERR_SET_VERSION_FAILED,
    IPSI_CMP_ERR_SET_HTTP_METHOD_FAILED,
    IPSI_CMP_ERR_SET_HTTP_URI_FAILED,
    IPSI_CMP_ERR_SET_HTTP_MSG_BODY_FAILED,
    IPSI_CMP_ERR_SET_HTTP_MERGE_SEND_FAILED,
    IPSI_CMP_ERR_HTTP_MSG_SEND_FAILED,
    IPSI_CMP_ERR_HTTP_CREATE_MSG_FAILED,
    IPSI_CMP_ERR_SERVER_IP_TOO_LARGE,
    IPSI_CMP_ERR_WRONG_SERVER_IP,
    IPSI_CMP_ERR_TIMER_CREAT_FAILED,
    IPSI_CMP_ERR_SET_TIMEOUT_FAILED,
    IPSI_CMP_ERR_TIMER_THREAD_CREATE_FAILED,
    IPSI_CMP_ERR_SET_SSL_CB_FAILED_HTTP_CTX_CREATED,
    IPSI_CMP_ERR_REGISTER_SSL_CB_FAILED,
    IPSI_CMP_ERR_HTTP_SET_REQ_DEST_ADDR_FAILED,
    IPSI_CMP_ERR_SSL_CB_NOT_REG,
    IPSI_CMP_ERR_REG_SOCKET_FUNC_FAILED,
    IPSI_CMP_ERR_REG_THREAD_FUNC_FAILED,
    IPSI_CMP_ERR_HTTP_STRING_TO_IP_ADDR_FAILED,
    IPSI_CMP_HTTP_ERR_SETTING_SRC_IP_ADDR_FAILED,
    IPSI_CMP_HTTP_ERR_INVALID_SOCK_OPTIONS,
    IPSI_CMP_HTTP_ERR_SETTING_SOCK_OPT_FAILED,
    IPSI_CMP_ERR_REG_READ_WRITE_LOCK_FUNC_FAILED,
    IPSI_CMP_ERR_HTTP_SET_MAX_INSTANCE_NUMBER_FAILED,
    IPSI_CMP_ERR_HTTP_API_INIT_FAILED,
    IPSI_CMP_ERR_HTTP_METHOD_ALREADY_INIT,
    IPSI_CMP_ERR_SET_CONN_TIMEOUT_FAILED,
    IPSI_CMP_ERR_SET_METHOD_CONFIG_PARAM_FAILED,
    IPSI_CMP_ERR_HTTP_MAX
};

#ifdef __cplusplus
}
#endif

#endif
