
#include "pme_app/pme_app.h"
#include "bios_ipmi.h"
#include "bios_cert.h"
#include "bios.h"
#include "verify.h"

LOCAL gint32 reboot_request_process(REBOOT_CTRL ctrl)
{
    if (ctrl == REBOOT_PREPARE) {
        wait_encrypted_biospwd_rollback();
        return RET_OK;
    }

    
    if (ctrl == REBOOT_FORCE || ctrl == REBOOT_PERFORM) {
        (void)per_exit();
        return RET_OK;
    }

    if (ctrl == REBOOT_CANCEL) {
        return RET_OK;
    }

    return RET_OK;
}

// 1) 注册模块，必须填写
// 2) 注册管理的类, 如果有则填写，没有不填写
// 3) 注册类的方法实现，如果有则填写，没有不填写
// 4) 注册需要持久化的数据，如果有静态的可以填写，如果依赖对象的，在代码中动态添加
// 5) 注册需要处理的IPMI命令，如果有则填写，没有不填写
// 6) 注册reboot善后处理函数，如果有则填写，没有不填写
// 7) 注册增量文件，如果有则填写，没有不填写
// 8) 注册调试命令，如果有则填写，没有不填写
// 同类型的注册请连续放在一起便于维护。
BEGIN_MODULE_DECLARATION(MODULE_NAME_BIOS)
// -- 本模块需要管理的类声明: class name(<=32 bytes)
DECLARATION_CLASS(SMBIOS_CLASS_NAME)
DECLARATION_CLASS(BIOS_CLASS_NAME)
DECLARATION_CLASS(ETH_CLASS_NAME_OSCAPORT) // osca类名注册

// -- 类方法实现声明: class name(<=32 bytes), property name(<=32 bytes), callback function
// 新需求AR586D337A-B0EF-49da-B718-473CC926DAA9
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_PRINT_FLAG, bios_set_print_flag)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_BOOTOPTION, bios_set_start_option)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_BOOTOPTION_EXT, bios_set_start_option_ext)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_BOOTOPTION_FLAG, bios_set_start_option_flag)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_BOOTOPTION_FLAG_EXT, bios_set_start_option_flag_ext)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_CLEARCMOS, bios_clear_cmos)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SMBIOS, bios_clear_smbios)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BOOT_ORDER, method_set_boot_order)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_BOOT_MODE, bios_set_boot_mode)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_BOOT_MODE_SW, bios_set_boot_mode_sw)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_BOOT_MODE_SW_ENABLE, bios_set_boot_mode_sw_enable)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_GET_BOOT_ORDER, method_get_boot_order)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_CONFIG, bios_get_config)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_CONFIG, bios_set_config)


DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_NOTIFY_PCIE_INFO, bios_notify_pcie_info)



DECLARATION_CLASS_METHOD(SMBIOS_CLASS_NAME, METHOD_SMBIOS_SET_VERSION, smbios_set_version)
DECLARATION_CLASS_METHOD(SMBIOS_CLASS_NAME, METHOD_SMBIOS_SET_SKUNUMBER, smbios_set_skunumber)
DECLARATION_CLASS_METHOD(SMBIOS_CLASS_NAME, METHOD_SMBIOS_SET_FAMILY, smbios_set_family)



DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_STARTUP_STATE, bios_set_system_startup_state)



DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_JSON_FILE, bios_get_json_file)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_JSON_FILE, bios_set_json_file)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_RESET, bios_reset)


DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_REVOKE_BIOSSETTING, clear_bios_setting_file)


DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_CLP_RESP, Bios_Get_Clp_Response)


DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_CLP_CONF, Bios_Set_Clp_Config)


DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_SETTING_EFFECTIVE_STATUS, bios_get_setting_effective_status)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_CHANGE_PWD, method_bios_change_password)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_UPDATE_CIPHERTEXT, kmc_update_bios_ciphertext)

DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_ENERGY_MODE_ENABLE, bios_set_energy_mode_enable)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_DYNAMIC_CONFIGURATION, bios_set_dynamic_configuration)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_DEMT_ENABLE, bios_set_demt_state)

#ifdef ARM64_HI1711_ENABLED
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_VERIFY_BIOS_FIRMWARE, method_verify_bios_firmware)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_SET_BIOS_FW_VERIFY_RESULT, method_set_bios_fw_verify_result)
#endif
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_FLASH_ID, set_flash_id)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_CERTIFICATES, method_bios_get_cert)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_HTTPS_CERTIFICATES, method_bios_get_https_cert)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_IMPORT_CERT, method_bios_import_cert)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_RESET_CERT, method_bios_reset_cert)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_GET_SECUREBOOT, method_bios_get_secureboot)
DECLARATION_CLASS_METHOD(BIOS_CLASS_NAME, METHOD_BIOS_SET_SECUREBOOT, method_bios_set_secureboot)
// -- reboot 请求处理函数
// -- 软件需要复位时，会向所有进程广播reboot消息，各个模块做退出善后处理(关闭文件、释放资源等)。如果无需处理可以不用注册
DECLARATION_REBOOT_PROCESS(reboot_request_process)

// -- 添加对象处理
// -- 对象添加后，模块可能需要管理新增的对象
// ON_ADD_OBJECT(NULL) // ? 是否要加类名?
// -- 删除对象处理
// -- 对象删除后，模块可能需要做一些清理处理
// ON_DEL_OBJECT(NULL)
// -- 本模块dump信息导出回调处理函数
ON_DUMP(bios_dump_info)
// -- 监听属性变更事件
// -- 监听其他类属性变更事件回调. 如果监听指定对象事件需动态添加


// ON_CLASS_PROPERTY_EVENT("OtherClass", "Property1", NULL, NULL)

ON_CLASS_PROPERTY_EVENT(CLASS_CHASSISPAYLOAD, PROPERTY_PAYLOAD_CHASSPWR_STATE, smbios_set_smbios_status_default_value,
    NULL)
ON_CLASS_PROPERTY_EVENT(CLASS_CHASSISPAYLOAD, PROPERTY_PAYLOAD_RESET_FLAG, smbios_set_smbios_status_default_value, NULL)
ON_CLASS_PROPERTY_EVENT(CLASS_CHASSISPAYLOAD, PROPERTY_PAYLOAD_SYS_RST_FLAG, smbios_set_smbios_status_default_value,
    NULL)

ON_CLASS_PROPERTY_EVENT(CLASS_CHASSISPAYLOAD, PROPERTY_PAYLOAD_RESTART_VALUE,
    bios_set_system_startup_state_default_value, NULL)

ON_CLASS_PROPERTY_EVENT(PFN_CLASS_NAME, PFN_UPGRADED_FLAG, roll_back_bios_pwd, NULL)
ON_CLASS_PROPERTY_EVENT(PFN_CLASS_NAME, PFN_PREROLLBACK_FLAG, roll_back_bios_pwd, NULL)
ON_CLASS_PROPERTY_EVENT(SMBIOS_CLASS_NAME, PROPERTY_SMBIOS_STATUS_VALUE, clear_boot_cert_file, NULL)
ON_CLASS_PROPERTY_EVENT(CLASS_HOSTMU, PROPERTY_HOSTMU_BOOT_STAGE, on_hostmu_bootstage_change, NULL)
END_MODULE_DECLARATION()

// -- 支持的IPMI命令声明: netfn, cmd, filter(e.g. "data[0]=1,data[2]=3"), privilege, maxlen, minlen, callback function
BEGIN_IPMI_COMMAND()
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=3h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 5, 5, bios_update_bios_status, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=2h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 36, BIOS_IPMI_CMD_MIN_LEN, bios_set_bios_ver, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=4Ah", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 6, bios_set_teeos_info, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=4h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 6, bios_write_smbios_data, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=9h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 8, bios_write_file_to_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=ah", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_IPMI_CMD_MAX_LEN, 7, bios_read_file_from_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=bh", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 8, 8, bios_set_file_changed, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=ch", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 6, 5, bios_get_file_changed, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=05h,data[4]=10h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_BASICSETTING, 0xff, 6, bios_update_post_status, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=05h,data[4]=11h,data[6]=00h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_BASICSETTING, 0xff, 0x07,
    bios_set_certificate_overdue_status, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=05h,data[4]=11h,data[6]=01h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_BASICSETTING, 0xff, 0x07,
    bios_set_certificate_overdue_status, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=05h,data[4]=11h,data[6]=02h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_BASICSETTING, 0x08, 0x08, bios_set_memory_mismatch, NULL)

ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=0h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=1h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=2h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=3h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=4h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=5h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=6h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=7h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=80h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=81h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=82h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=83h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=84h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=85h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=86h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=87h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 8, "data[0]=63h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 2, bios_set_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=0h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=1h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=2h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=3h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=4h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=5h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=6h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=7h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=80h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=81h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=82h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=83h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=84h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=85h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=86h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=87h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_CHASSIS_REQ, 9, "data[0]=63h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_GET_BOOT_OPTION_LEN, BIOS_GET_BOOT_OPTION_LEN, bios_get_system_boot_options, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_SHMC_CMDNUM, "data[3]=5h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 6, upload_resource_to_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_SHMC_CMDNUM, "data[3]=6h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 6, download_resource_from_bmc, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_SHMC_CMDNUM, "data[3]=3eh", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 6, get_file_checksum_from_bmc, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=Fh", RMCP_USER | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_READONLY, BIOS_IPMI_CMD_MAX_LEN, BIOS_ADD_LOG_MIN_LEN, bios_add_log_entry, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, BIOS_IPMI_CMD_CMDNUM, "data[3]=22h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, BIOS_IPMI_CMD_MAX_LEN, BIOS_GET_REGISTER_INFO_MIN_LEN, bios_get_hardware_register_info,
    NULL)




ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=00h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=01h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=02h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=03h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=04h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=05h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=06h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_SET_SYSTEM_INFO_PARAMETERS, "data[0]=07h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, BIOS_IPMI_CMD_MAX_LEN, 0x02,
    ipmi_set_system_info_parameters, NULL)


ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=c1h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0x04, 0x04, ipmi_set_osca_port_type, NULL)


ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=00h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=01h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=02h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=03h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=04h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=05h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=06h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, IPMI_GET_SYSTEM_INFO_PARAMETERS, "data[1]=07h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0x04, 0x04, ipmi_get_system_info_parameters, NULL)



ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x59, "data[1]=c1h", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW, PROPERTY_USERROLE_READONLY,
    0x04, 0x04, ipmi_get_osca_port_type, NULL)

ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=c6h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 0x02, bios_write_bdf_data_to_bmc, NULL)


ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=c8h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 0x02, bios_write_bdf_data_to_bmc, NULL)


ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=cch", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 0x02, bios_write_bdf_data_to_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=d0h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 0x02, bios_write_bdf_data_to_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_APP_REQ, 0x58, "data[0]=d1h", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 0x02, bios_write_bdf_data_to_bmc, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, IPMI_OEM_SYS_COMMAND, "data[3]=47h", RMCP_ADMIN | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_USERMGNT, 8, 8, ipmi_bios_change_pwd, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, IPMI_OEM_SYS_COMMAND, "data[3]=2Eh", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 8, 8, bios_get_dynamic_configuration, NULL)
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, IPMI_OEM_SYS_COMMAND, "data[3]=2Fh", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0xff, 9, bios_set_dynamic_config_result, NULL)
#ifdef ARM64_HI1711_ENABLED
ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, 0x90, "data[0]=59h,data[1]=0dh", RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID,
    PROPERTY_USERROLE_BASICSETTING, 0x04, 0x02, ipmi_get_bios_gold_valid, NULL)
#endif

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, 0x93, "data[3]=5ah,data[4]=1ch,data[5]=00h",
    RMCP_OPERATOR | IPMI_SYS_LOCKDOWN_FORBID, PROPERTY_USERROLE_BASICSETTING, 11, 11, ipmi_set_bios_config_item, NULL)

ADD_IPMI_COMMAND_V2(NETFN_OEM_REQ, 0x92, "data[3]=1ah", RMCP_USER | IPMI_SYS_LOCKDOWN_ALLOW,
    PROPERTY_USERROLE_READONLY, 0xff, 0x05, ipmi_cmd_get_property_from_bios_file, NULL)

END_IPMI_COMMAND()

// -- 支持的debug调试命令声明
// -- 用于模块调试
BEGIN_DEUBG_COMMAND()
ADD_DEBUG_COMMAND("boot_option", bios_show_boot_options, "", "Usage: boot_option\nShow boot options info.\n")
ADD_DEBUG_COMMAND("file_change", bios_show_file_change, "", "Usage: file_change\nShow file change info.\n")
ADD_DEBUG_COMMAND("data_operation", bios_show_data_operations, "",
    "Usage: data_operation\nShow data operations info.\n")
ADD_DEBUG_COMMAND("upload_fw", show_upload_firmware_info, "", "Usage: upload_fw\nShow upload firmware info.\n")
END_DEBUG_COMMAND()

// -- 模块初始化及处理，必填
BEGIN_MODULE_MAIN()
#ifdef ITEST
iTest_Init(argc, argv);
#endif
// -- 本模块实现的初始化函数，可选
MODULE_INIT(bios_init)
MODULE_START(bios_start)
#ifdef ITEST
start_tshell_main(argc, argv);
#endif
END_MODULE_MAIN()
