/* ****************************************************************************

 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
                            ALL RIGHTS RESERVED

------------------------------------------------------------------------------

FileName     : crypto_error.h
 * Author: VPP
Version      : 1
Description  : This file contains crypto errors
 * Create: 2012/10/20
Function List: OSI_bits
uLong_bits
uLong_I2OSP
uLong_OS2IP

          History:  <author>   <date>          <desc>
----------------------------------------------------------------------------
*************************************************************************** */
#ifndef CRYPTO_ERROR_H
#define CRYPTO_ERROR_H

#include "common_error.h"
#include "sec_sys.h"

#ifndef _FIPS_IPSI_CRYPTO_ERROR_H

/* All error codes starts from this value for this module */
#define SEC_CRYPT_ERR_BASE 0x73020000UL
#define DEFINE_CRYPTO_ERR(v) (SEC_CRYPT_ERR_BASE + (v))

#define SEC_CRYPT_ERR_INVALID_PKEY DEFINE_CRYPTO_ERR(1)
#define SEC_CRYPT_ERR_UNDEFINED_KEY_OPERATION DEFINE_CRYPTO_ERR(2)
#define SEC_CRYPT_ERR_UNDEFINED_PADDING DEFINE_CRYPTO_ERR(3)
#define SEC_CRYPT_ERR_INVALID_CTX DEFINE_CRYPTO_ERR(4)
#define SEC_CRYPT_ERR_INVALID_PKEY_TYPE DEFINE_CRYPTO_ERR(5)
#define SEC_CRYPT_ERR_LARGE_DATA_SIZE DEFINE_CRYPTO_ERR(6)
#define SEC_CRYPT_ERR_SMALL_DATA_SIZE DEFINE_CRYPTO_ERR(7)
#define SEC_CRYPT_ERR_INVALID_PADDING DEFINE_CRYPTO_ERR(8)
#define SEC_CRYPT_ERR_UNDEFINED_FIELD DEFINE_CRYPTO_ERR(9)
#define SEC_ERR_INVALID_PUB_KEY_E_LENGTH DEFINE_CRYPTO_ERR(10)
#define SEC_ERR_INVALID_PUB_KEY_N_LENGTH DEFINE_CRYPTO_ERR(11)
#define SEC_ERR_NON_RSA_KEY DEFINE_CRYPTO_ERR(12)
#define SEC_ERR_NO_KEY DEFINE_CRYPTO_ERR(13)
#define SEC_ERR_DATA_GREATER_THAN_KEY_LEN DEFINE_CRYPTO_ERR(14)
#define SEC_CRYPT_ERR_AAD_LEN_EXCEED_MAXLIMIT DEFINE_CRYPTO_ERR(15)
#define SEC_CRYPT_ERR_INVALID_TAG_LEN DEFINE_CRYPTO_ERR(16)
#define SEC_CRYPT_ERR_IV_LEN_EXCEED_MAXLIMIT DEFINE_CRYPTO_ERR(17)
#define SEC_CRYPT_ERR_SET_AAD_AFTER_CIPHER_OPERATION DEFINE_CRYPTO_ERR(18)

#define SEC_CRYPT_ERR_SELF_TEST_FAIL DEFINE_CRYPTO_ERR(19)
#define SEC_CRYPT_ERR_DRBG_HEALTH_TEST_FAIL DEFINE_CRYPTO_ERR(20)
#define SEC_CRYPT_ERR_DRBG_INSTANTIATE_RETRIEVING_ENTROPY DEFINE_CRYPTO_ERR(21)
#define SEC_CRYPT_ERR_RETRIEVING_NONCE DEFINE_CRYPTO_ERR(22)
#define SEC_CRYPT_ERR_DRBG_INSTANTIATION DEFINE_CRYPTO_ERR(23)
#define SEC_CRYPT_ERR_UNSUPPORTED_DRBG_TYPE DEFINE_CRYPTO_ERR(24)
#define SEC_CRYPT_ERR_ERROR_INITIALISING_DRBG DEFINE_CRYPTO_ERR(25)
#define SEC_CRYPT_ERR_PERSONALISATION_STRING_TOO_LONG DEFINE_CRYPTO_ERR(26)
#define SEC_CRYPT_ERR_DRBG_NOT_INITIALISED DEFINE_CRYPTO_ERR(27)
#define SEC_CRYPT_ERR_DRBG_INSTANTIATE_IN_ERROR_STATE DEFINE_CRYPTO_ERR(28)
#define SEC_CRYPT_ERR_DRBG_ALREADY_INSTANTIATED DEFINE_CRYPTO_ERR(29)
#define SEC_CRYPT_ERR_DRBG_GENERATE_IN_ERROR_STATE DEFINE_CRYPTO_ERR(30)
#define SEC_CRYPT_ERR_DRBG_GENERATE_NOT_INSTANTIATED DEFINE_CRYPTO_ERR(31)
#define SEC_CRYPT_ERR_REQUEST_TOO_LARGE_FOR_DRBG DEFINE_CRYPTO_ERR(32)
#define SEC_CRYPT_ERR_DRBG_ADDITIONAL_INPUT_TOO_LONG DEFINE_CRYPTO_ERR(33)
#define SEC_CRYPT_ERR_DRBG_RESEED_IN_ERROR_STATE DEFINE_CRYPTO_ERR(34)
#define SEC_CRYPT_ERR_DRBG_RESEED_NOT_INSTANTIATED DEFINE_CRYPTO_ERR(35)
#define SEC_CRYPT_ERR_DRBG_RESEED_RETRIEVING_ENTROPY DEFINE_CRYPTO_ERR(36)
#define SEC_CRYPT_DRBG_RESEED_ERROR DEFINE_CRYPTO_ERR(37)
#define SEC_CRYPT_DRBG_GENERATE_ERROR DEFINE_CRYPTO_ERR(38)
#define SEC_CRYPT_DRBG_ERROR_RETRIEVING_ADDITIONAL_INPUT DEFINE_CRYPTO_ERR(39)

#endif

#endif /* _IPSI_CRYPTO_ERROR_H */
