/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2020. All rights reserved.
 * Description: 部件管理相关的定义。
 * Author: h00282621
 * Create: 2020-3-10
 * Notes: 用于跨模块使用的相关的定义。
 */

#ifndef __COMPONENT_DEFINE_H__
#define __COMPONENT_DEFINE_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

/* 设备类型定义，此定义废弃，不再允许扩展，改为使用下面的COMPONENT_TYPE */
typedef enum device_type {
    DEVICE_TYPE_CPU = 0,
    DEVICE_TYPE_MEMORY,
    DEVICE_TYPE_HARDDISK,
    DEVICE_TYPE_PS,
    DEVICE_TYPE_FAN,
    DEVICE_TYPE_HDD_BACKPLANE,
    DEVICE_TYPE_RAID_CARD,
    DEVICE_TYPE_ETHERNET_CARD, // 代表网口
    DEVICE_TYPE_PCIE_CARD,
    DEVICE_TYPE_MMC,
    DEVICE_TYPE_HBA,
    DEVICE_TYPE_MEZZ,
    DEVICE_TYPE_UPGRADE_ROM,
    DEVICE_TYPE_NIC_CARD, // 网卡插卡，只是代表插卡，不包括上面的网口
    DEVICE_TYPE_MEMORY_RISER,
    DEVICE_TYPE_PCIE_RISER,
    DEVICE_TYPE_MAINBOARD,
    DEVICE_TYPE_LCD,
    DEVICE_TYPE_BOARD_CPU,
    DEVICE_TYPE_BOARD_MEMORY,
    DEVICE_TYPE_BOARD_IO,
    DEVICE_TYPE_BOARD_HDPLANE,
    DEVICE_TYPE_BOARD_PCIERISER,
    DEVICE_TYPE_BOARD_MAIN,
    DEVICE_TYPE_CHASSIS_BACKPLANE = 22,
    DEVICE_TYPE_FAN_BOARD = 24,
    DEVICE_TYPE_BMC = 26,
    DEVICE_TYPE_IO_BOARD = 35,
    DEVICE_TYPE_PATCH_BOARD = 38,
    DEVICE_TYPE_SDI_CARD = 57, // SDI卡 增加子类
    DEVICE_TYPE_MIN_SAS = 58,
    DEVICE_TYPE_SATA_DOM = 59,
    DEVICE_TYPE_GE = 60,
    DEVICE_TYPE_XGE = 61,
    DEVICE_TYPE_PCIE_SWITCH = 62, // 新增PcieSwitch类
    DEVICE_TYPE_GPU_BOARD = 64,
    DEVICE_TYPE_BBU = 82,	
    DEVICE_TYPE_LEAK_DET_CARD = 84,
    DEVICE_TYPE_NPU = 86
} DEVICE_TYPE;


/* 事件主体部件类型 */
typedef enum {
    COMPONENT_TYPE_CPU = 0,
    COMPONENT_TYPE_MEMORY,
    COMPONENT_TYPE_HARDDISK,
    COMPONENT_TYPE_PS,
    COMPONENT_TYPE_FAN,
    COMPONENT_TYPE_HDD_BACKPLANE,
    COMPONENT_TYPE_RAID_CARD,
    COMPONENT_TYPE_ETHERNET_CARD, // 代表网口
    COMPONENT_TYPE_PCIE_CARD,
    COMPONENT_TYPE_MMC,
    COMPONENT_TYPE_HBA = 10,
    COMPONENT_TYPE_MEZZ,
    COMPONENT_TYPE_UPGRADE_ROM,
    COMPONENT_TYPE_NIC_CARD, // 网卡插卡，只是代表插卡，不包括上面的网口
    COMPONENT_TYPE_MEMORY_RISER,
    COMPONENT_TYPE_PCIE_RISER,
    COMPONENT_TYPE_MAINBOARD,
    COMPONENT_TYPE_LCD,
    COMPONENT_TYPE_CHASSIS,
    COMPONENT_TYPE_NCM,
    COMPONENT_TYPE_SWITCH_MODULE = 20,
    COMPONENT_TYPE_STORAGE_BOARD,
    COMPONENT_TYPE_CHASSIS_BACKPLANE,
    COMPONENT_TYPE_HMM,
    COMPONENT_TYPE_FAN_BACKPLANE,
    COMPONENT_TYPE_PSU_BACKPLANE,
    COMPONENT_TYPE_BMC,
    COMPONENT_TYPE_MM_MMC,
    COMPONENT_TYPE_TWIN_NODE_BACKPLANE,
    COMPONENT_TYPE_BASE_PLANE,
    COMPONENT_TYPE_FABRIC_PLANE = 30,
    COMPONENT_TYPE_SWITCH_MEZZ,
    COMPONENT_TYPE_LED,
    COMPONENT_TYPE_SD_CARD,
    COMPONENT_TYPE_SECURITY_MODULE,
    COMPONENT_TYPE_IO_BOARD,
    COMPONENT_TYPE_BOARD_CPU,
    COMPONENT_TYPE_BOARD_RMC,
    COMPONENT_TYPE_BOARD_PCIE_ADAPTER,
    COMPONENT_TYPE_PCH,
    COMPONENT_TYPE_CABLE = 40,
    COMPONENT_TYPE_PORT,
    COMPONENT_TYPE_LSW,
    COMPONENT_TYPE_PHY,
    COMPONENT_TYPE_SYSTEM,
    COMPONENT_TYPE_EXPAND_BOARD,
    COMPONENT_TYPE_LED_BOARD,
    COMPONENT_TYPE_LPM,
    COMPONENT_TYPE_PIC_CARD,
    COMPONENT_TYPE_BUTTON,
    COMPONENT_TYPE_EXPANDER = 50,
    COMPONENT_TYPE_CPI,
    COMPONENT_TYPE_ACM,
    COMPONENT_TYPE_CIM,
    COMPONENT_TYPE_PFM,
    COMPONENT_TYPE_KPAR,
    COMPONENT_TYPE_JC,
    COMPONENT_TYPE_GPU_BOARD = 64,
    COMPONENT_TYPE_PASS_THROUGH_CARD = 67,
    COMPONENT_TYPE_HORIZ_CONN_BRD = 76,
    COMPONENT_TYPE_ASSET_LOCATE_BRD = 78,
    COMPONENT_TYPE_UNIT = 79,
    COMPONENT_TYPE_RMM = 80,
    COMPONENT_TYPE_RACK = 81,
	COMPONENT_TYPE_BATTERY = 82,	
    COMPONENT_TYPE_OCP = 83,
    /* BEGIN: UADP382658. Modified by f00381872, 2019/11/8 */
	COMPONENT_TYPE_LEAKDET_CARD = 84,
    COMPONENT_TYPE_MESH_CARD = 85,
    COMPONENT_TYPE_NPU = 86,
    COMPONENT_TYPE_CIC = 87,
    COMPONENT_TYPE_EPM = 88,
    COMPONENT_TYPE_FAN_MODULE = 89,
    COMPONENT_TYPE_AR_CARD = 90,  /* 北冰洋AR卡 */
    COMPONENT_TYPE_SOC_BOARD = 92,
    COMPONENT_TYPE_EXPBOARD = 93,
    COMPONENT_TYPE_INVALID = 255
} COMPONENT_DEVICE_TYPE_E;

typedef enum {
    TYPE_PCIE_CARD,
    TYPE_OCP,
    TYPE_RAID
} DEVICE_TYPE_E;

/* 以下定义需要整改代码，用上面的枚举替换 */
#define COMPONENT_TYPE_BACKPLANE_BOARD 22 // 需要整改代码，用上面的枚举替换
#define LOM_COMPONENT_TYPE 13
#define RAID_COMPONENT_TYPE 6
#define PCIE_COMPONENT_TYPE 8
#define MEZZ_COMPONENT_TYPE 11
#define PCIE_SSD_COMPONENT_TYPE 38
#define PCH_COMPONENT_TYPE 39

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __COMPONENT_DEFINE_H__ */
