/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2001-2020. All rights reserved.
 * Description: hi51 sram header file
 */
#ifndef _HI51_SRAM_H_
#define _HI51_SRAM_H_

#ifdef DEBUG_C51
#define SRAM_BASE_ADDR          0x00000000UL
#else
#define SRAM_BASE_ADDR          0x11000000UL
#endif

/*
 * 0x0000~0x4FFF: CODE    代码区
 * 0x5000~0x8FFF: REV1    保留区
 * 0x9000~0x9FFF: SYSTEM  系统保留区
 * 0xA000~0xAFFF: DATA_51 51管理的用户数据区
 * 0xB000~0xBFFF: DATA_A9 A9管理的用户数据区
 * 0xC000~0xCFFF: REV2    保留区
 * 0xE000~0xE0FF: SYS CFG 系统配置区
 * 0xE100~0xEFFF: USER CFG  用户配置区
 * 注意：SRAM使用须严格按照上面的区块划分。系统保留区用户不允许访问
 */
#define SRAM_BYTES              0xF000
#define SRAM_MAX_ADDR           (SRAM_BASE_ADDR | 0xEFFF)

#define SRAM_CODE_BASE_ADDR     (SRAM_BASE_ADDR | 0x0000)
#define SRAM_REV1_BASE_ADDR     (SRAM_BASE_ADDR | 0x5000)
#define SRAM_SYSTEM_DATA_BASE   (SRAM_BASE_ADDR | 0x9000)
#define SRAM_DATA_51_BASE_ADDR  (SRAM_BASE_ADDR | 0xA000)
#define SRAM_DATA_A9_BASE_ADDR  (SRAM_BASE_ADDR | 0xB000)
#define SRAM_REV2_BASE_ADDR     (SRAM_BASE_ADDR | 0xC000)
#define SRAM_CONFIG_SYS_BASE    (SRAM_BASE_ADDR | 0xE000)
#define SRAM_CONFIG_USER_BASE   (SRAM_BASE_ADDR | 0xE100)

#define SRAM_CODE_LENGTH        (SRAM_REV1_BASE_ADDR - SRAM_CODE_BASE_ADDR)
#define SRAM_REV1_LENGTH        (SRAM_SYSTEM_DATA_BASE - SRAM_REV1_BASE_ADDR)
#define SRAM_SYSTEM_DATA_LENGTH (SRAM_DATA_51_BASE_ADDR - SRAM_SYSTEM_DATA_BASE)
#define SRAM_DATA_51_LENGTH     (SRAM_DATA_A9_BASE_ADDR - SRAM_DATA_51_BASE_ADDR)
#define SRAM_DATA_A9_LENGTH     (SRAM_REV2_BASE_ADDR - SRAM_DATA_A9_BASE_ADDR)
#define SRAM_REV2_LENGTH        (SRAM_CONFIG_SYS_BASE - SRAM_REV2_BASE_ADDR)
#define SRAM_CONFIG_SYS_LENGTH  (SRAM_CONFIG_USER_BASE - SRAM_CONFIG_SYS_BASE)
#define SRAM_CONFIG_USER_LENGTH (SRAM_MAX_ADDR - SRAM_CONFIG_USER_BASE)

#endif